"use client";
import {Suspense,useEffect,useMemo,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import Hls from "hls.js";

type DownloadJob={id:string;title:string;url:string;type:"direct"|"hls";status:"queued"|"downloading"|"complete"|"failed";progress:number;createdAt:number;size?:number;blobUrl?:string;error?:string};

const DOWNLOAD_KEY="drift-downloads";
function loadDownloads():DownloadJob[]{try{return JSON.parse(localStorage.getItem(DOWNLOAD_KEY)||"[]")}catch{return[]}}
function saveDownloads(x:DownloadJob[]){localStorage.setItem(DOWNLOAD_KEY,JSON.stringify(x.map(({blobUrl,...j})=>j)))}
function proxyUrl(raw:string,ph:string){return "/api/media/proxy?url="+encodeURIComponent(raw)+(ph?"&ph="+encodeURIComponent(ph):"")}
async function downloadMedia(job:DownloadJob,ph:string,onUpdate:(p:number)=>void){
 const src=job.type==="hls"?proxyUrl(job.url,ph):proxyUrl(job.url,ph);
 if(job.type==="direct"){
   const r=await fetch(src);if(!r.ok)throw Error("Download request failed ("+r.status+")");
   const total=Number(r.headers.get("content-length")||0);let done=0;const reader=r.body?.getReader();const chunks:Uint8Array[]=[];
   if(reader){for(;;){const x=await reader.read();if(x.done)break;if(x.value){chunks.push(x.value);done+=x.value.byteLength;if(total)onUpdate(Math.min(99,done/total*100))}}}
   const blob=new Blob(chunks,{type:r.headers.get("content-type")||"video/mp4"});return URL.createObjectURL(blob);
 }
 const playlist=await (await fetch(src)).text();
 if(/#EXT-X-MAP:/i.test(playlist))throw Error("This HLS stream uses fragmented MP4; HLS download for this format is not available yet.");
 const lines=playlist.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const segs=lines.filter(x=>!x.startsWith("#"));
 if(!segs.length)throw Error("No HLS segments found.");
 const base=new URL(job.url);const chunks:BlobPart[]=[];
 for(let i=0;i<segs.length;i++){const u=segs[i].startsWith("/api/media/proxy")?new URL(segs[i],window.location.origin).toString():new URL(segs[i],base).toString();const rr=await fetch(u);if(!rr.ok)throw Error("Segment "+(i+1)+" failed ("+rr.status+")");chunks.push(await rr.blob());onUpdate(Math.min(99,((i+1)/segs.length)*100))}
 return URL.createObjectURL(new Blob(chunks,{type:"video/mp2t"}));
}
type Subtitle={url:string;lang?:string;label?:string;id?:string};
type Level={height:number;bitrate:number};
function P(){
 const p=useSearchParams(),u=p.get("url")||"",t=p.get("title")||"Drift Player",ph=p.get("ph")||"",id=p.get("id")||"",type=p.get("type")||"movie",poster=p.get("poster")||"",episodeId=p.get("episodeId")||"",season=p.get("season")||"",episode=p.get("episode")||"",nextId=p.get("nextId")||"",nextTitle=p.get("nextTitle")||"",nextSeason=p.get("nextSeason")||"",nextEpisode=p.get("nextEpisode")||"";
 const [addonUrls]=useState<string[]>(()=>{try{return JSON.parse(atob(p.get("addons")||""))||[]}catch{return[]}});
 const videoRef=useRef<HTMLVideoElement|null>(null),hlsRef=useRef<Hls|null>(null),hideRef=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [error,setError]=useState(""),[duration,setDuration]=useState(0),[resume,setResume]=useState(0),[fallbackIndex,setFallbackIndex]=useState(0),[fallbackName,setFallbackName]=useState(""),[candidates,setCandidates]=useState<{url:string;name?:string;title?:string;behaviorHints?:Record<string,unknown>}[]>([]);
 const [playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[volume,setVolume]=useState(1),[speed,setSpeed]=useState(1),[fullscreen,setFullscreen]=useState(false),[levels,setLevels]=useState<Level[]>([]),[level,setLevel]=useState(-1),[menu,setMenu]=useState<"cc"|"quality"|"speed"|null>(null),[showControls,setShowControls]=useState(true),[nextCountdown,setNextCountdown]=useState(0),[nextLoading,setNextLoading]=useState(false),[downloadMessage,setDownloadMessage]=useState("");
 const subs=useMemo<Subtitle[]>(()=>{try{return JSON.parse(atob(p.get("subs")||""))||[]}catch{return[]}},[p]);
 const progressKey=episodeId?(type+":"+episodeId):(id?(type+":"+id):("url:"+u));
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("drift-stream-candidates")||"[]");if(Array.isArray(x))setCandidates(x.filter((s:any)=>s?.url))}catch{}},[]);
 const active=candidates[fallbackIndex]?.url||u,activeHints:any=candidates[fallbackIndex]?.behaviorHints||{},activePh=fallbackIndex&&activeHints.proxyHeaders?.request?btoa(JSON.stringify(activeHints.proxyHeaders.request)):ph;
 const isHls=/\.m3u8(\?|$)/i.test(active),isMedia=/\.(mp4|webm|ogg)(\?|$)/i.test(active);
 const touchControls=()=>{setShowControls(true);if(hideRef.current)clearTimeout(hideRef.current);hideRef.current=setTimeout(()=>setShowControls(false),3500)};
 useEffect(()=>{try{const all=JSON.parse(localStorage.getItem("drift-progress")||"{}");const item=all[progressKey];if(item?.position>5&&item?.position<Math.max(item.duration-30,0))setResume(item.position)}catch{}},[progressKey]);
 useEffect(()=>{const v=videoRef.current;if(!v||!u)return;setError("");const save=()=>{try{const all=JSON.parse(localStorage.getItem("drift-progress")||"{}");all[progressKey]={id,type,title:t,poster,url:u,ph,subs,episodeId,season,episode,position:v.currentTime||0,duration:v.duration||duration,updatedAt:Date.now()};localStorage.setItem("drift-progress",JSON.stringify(all))}catch{}};const onTime=()=>{setCurrent(v.currentTime);if(Math.floor(v.currentTime)%5===0)save()};const onPlay=()=>setPlaying(true),onPause=()=>{setPlaying(false);save()};const onLoaded=()=>{setDuration(v.duration||0);if(resume>0&&resume<v.duration-30){try{v.currentTime=resume}catch{}}};const onEnded=()=>{try{const all=JSON.parse(localStorage.getItem("drift-progress")||"{}");delete all[progressKey];localStorage.setItem("drift-progress",JSON.stringify(all))}catch{};if(nextId)setNextCountdown(5)};const onVideoError=()=>{if(fallbackIndex+1<candidates.length){setFallbackIndex(x=>x+1);setFallbackName(candidates[fallbackIndex+1].name||candidates[fallbackIndex+1].title||"another stream");setError("Playback failed. Trying another available stream…")}else setError("The video could not be played. The stream may have expired or rejected the request.")};
 v.addEventListener("timeupdate",onTime);v.addEventListener("play",onPlay);v.addEventListener("pause",onPause);v.addEventListener("loadedmetadata",onLoaded);v.addEventListener("ended",onEnded);v.addEventListener("error",onVideoError);
 if(isHls){if(Hls.isSupported()){const h=new Hls({enableWorker:false,lowLatencyMode:false,backBufferLength:90});hlsRef.current=h;h.attachMedia(v);h.on(Hls.Events.MANIFEST_PARSED,()=>{setLevels(h.levels.map(x=>({height:x.height||0,bitrate:x.bitrate||0})));v.play().catch(()=>{})});h.loadSource("/api/media/proxy?url="+encodeURIComponent(active)+(activePh?"&ph="+encodeURIComponent(activePh):""));h.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal){if(fallbackIndex+1<candidates.length){setFallbackIndex(x=>x+1);setFallbackName(candidates[fallbackIndex+1].name||candidates[fallbackIndex+1].title||"another stream");setError("This stream failed. Trying another available stream…")}else setError("HLS playback failed. All available streams failed.")}});return()=>{h.destroy();hlsRef.current=null}}if(v.canPlayType("application/vnd.apple.mpegurl"))v.src=active;else setError("This browser does not support HLS playback.")}else if(isMedia)v.src=active;else setError("This stream is not a browser-native media URL.");
 return()=>{v.removeEventListener("timeupdate",onTime);v.removeEventListener("play",onPlay);v.removeEventListener("pause",onPause);v.removeEventListener("loadedmetadata",onLoaded);v.removeEventListener("ended",onEnded);v.removeEventListener("error",onVideoError)};
 },[active,isHls,isMedia,activePh,progressKey,t,type,poster,subs,fallbackIndex,candidates.length,resume,nextId]);
 useEffect(()=>{if(!nextCountdown)return;const timer=setTimeout(()=>{if(nextCountdown<=1)goNext();else setNextCountdown(x=>x-1)},1000);return()=>clearTimeout(timer)},[nextCountdown]);
 async function startDownload(){
  if(isHls){setDownloadMessage("HLS download needs remuxing to a real video file; Drift will not give you a raw .ts file.");return} const hls=isHls;const job:DownloadJob={id:crypto.randomUUID(),title:t,url:active,type:hls?"hls":"direct",status:"queued",progress:0,createdAt:Date.now()};
  const all=[job,...loadDownloads()];saveDownloads(all);setNoticeForDownload(job.id,"downloading");
  try{const blobUrl=await downloadMedia(job,activePh,p=>updateDownload(job.id,{status:"downloading",progress:p}));const done=loadDownloads().find(x=>x.id===job.id);updateDownload(job.id,{status:"complete",progress:100});const a=document.createElement("a");a.href=blobUrl;a.download=safeFileName(t)+(hls?".ts":guessExt(active));a.click();setTimeout(()=>URL.revokeObjectURL(blobUrl),60000);if(done){} }catch(e){updateDownload(job.id,{status:"failed",progress:0,error:e instanceof Error?e.message:"Download failed"})}
 }
 function updateDownload(id:string,patch:Partial<DownloadJob>){const next=loadDownloads().map(x=>x.id===id?{...x,...patch}:x);saveDownloads(next)}
 function setNoticeForDownload(id:string,status:"downloading"){updateDownload(id,{status,progress:0})}
 async function goNext(){if(!nextId||nextLoading)return;setNextLoading(true);try{const rs=await Promise.all(addonUrls.map(async a=>{try{const r=await fetch("/api/addon/resource?addon="+encodeURIComponent(a)+"&resource=stream&type="+type+"&id="+encodeURIComponent(nextId));if(!r.ok)return[];const j=await r.json();return j.streams||[]}catch{return[]}}));const all=rs.flat().filter((s:any)=>s?.url);if(!all.length){setError("Next episode has no playable stream.");setNextCountdown(0);return}localStorage.setItem("drift-stream-candidates",JSON.stringify(all.slice(0,12)));const s=all[0],h=s.behaviorHints||{},sp=new URLSearchParams({url:s.url,title:nextTitle||"Next episode",ph:btoa(JSON.stringify(h.proxyHeaders?.request||{})),id,type,poster,subs:btoa(JSON.stringify(s.subtitles||[])),episodeId:nextId,season:nextSeason,episode:nextEpisode,nextId:"",nextTitle:"",nextSeason:"",nextEpisode:"",addons:btoa(JSON.stringify(addonUrls))});window.location.href="/watch?"+sp.toString()}finally{setNextLoading(false)}}
 async function togglePlay(){const v=videoRef.current;if(!v)return;if(v.paused)await v.play();else v.pause();touchControls()}
 function seek(delta:number){const v=videoRef.current;if(v){v.currentTime=Math.max(0,Math.min(v.duration||0,v.currentTime+delta));touchControls()}}
 async function toggleFullscreen(){const v=videoRef.current;if(!v)return;try{if(!document.fullscreenElement){await v.requestFullscreen?.();setFullscreen(true)}else{await document.exitFullscreen();setFullscreen(false)}}catch{}}
 function changeQuality(i:number){if(hlsRef.current){hlsRef.current.currentLevel=i;setLevel(i)}setMenu(null)}
 function chooseSpeed(x:number){const v=videoRef.current;if(v){v.playbackRate=x;setSpeed(x)}setMenu(null)}
 function chooseSubtitle(s:Subtitle){const v=videoRef.current;if(!v)return;v.querySelectorAll("track[data-drift]").forEach(x=>x.remove());const tr=document.createElement("track");tr.kind="subtitles";tr.label=s.label||s.lang||"Subtitle";tr.srclang=s.lang||"en";tr.src="/api/media/proxy?url="+encodeURIComponent(s.url)+(ph?"&ph="+encodeURIComponent(ph):"");tr.default=true;tr.setAttribute("data-drift","1");v.appendChild(tr);setTimeout(()=>{for(let i=0;i<v.textTracks.length;i++)v.textTracks[i].mode=i===v.textTracks.length-1?"showing":"disabled"},0);setMenu(null)}
 return <main className="watch"><a className="back" href="/">← Drift</a><div className="watchTitle"><h1>{t}</h1>{type==="series"&&season&&episode?<span className="episodeBadge">S{season} E{episode}</span>:null}{fallbackName&&<span>{fallbackName}</span>}</div>
 <div className="playerShell" onMouseMove={touchControls} onTouchStart={touchControls}>
 {isHls||isMedia?<video ref={videoRef} className="video" playsInline preload="metadata" poster={poster} onClick={togglePlay}/>:<div className="playerNotice"><h2>Stream resolved</h2><p>This stream uses a transport Drift browser player does not support yet.</p><code>{u}</code></div>}
 {(isHls||isMedia)&&showControls&&<div className="controlsOverlay"><div className="seekRow"><button onClick={()=>seek(-10)}>↶ 10</button><button className="bigPlay" onClick={togglePlay}>{playing?"❚❚":"▶"}</button><button onClick={()=>seek(10)}>10 ↷</button></div><input className="seekBar" type="range" min="0" max={duration||0.1} step="0.1" value={Math.min(current,duration||0)} onChange={e=>{const v=videoRef.current;if(v)v.currentTime=Number(e.target.value);touchControls()}}/><div className="controlBar"><button onClick={togglePlay}>{playing?"❚❚":"▶"}</button><span>{fmt(current)} / {fmt(duration)}</span><label>🔊<input className="volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={e=>{const x=Number(e.target.value);setVolume(x);if(videoRef.current)videoRef.current.volume=x}}/></label>{levels.length>1&&<div className="menuBox"><button onClick={()=>setMenu(menu==="quality"?null:"quality")}>{level<0?"Auto":(levels[level]?.height?levels[level].height+"p":"Quality")}</button>{menu==="quality"&&<div className="popMenu"><button onClick={()=>changeQuality(-1)}>Auto</button>{levels.map((x,i)=><button key={i} onClick={()=>changeQuality(i)}>{x.height?x.height+"p":Math.round(x.bitrate/1000)+" kbps"}</button>)}</div>}</div>}<div className="menuBox"><button onClick={()=>setMenu(menu==="speed"?null:"speed")}>{speed}×</button>{menu==="speed"&&<div className="popMenu"><button onClick={()=>chooseSpeed(.75)}>.75×</button><button onClick={()=>chooseSpeed(1)}>1×</button><button onClick={()=>chooseSpeed(1.25)}>1.25×</button><button onClick={()=>chooseSpeed(1.5)}>1.5×</button><button onClick={()=>chooseSpeed(2)}>2×</button></div>}</div>{subs.length>0&&<div className="menuBox"><button onClick={()=>setMenu(menu==="cc"?null:"cc")}>CC</button>{menu==="cc"&&<div className="popMenu">{subs.map((s,i)=><button key={s.id||i} onClick={()=>chooseSubtitle(s)}>{s.label||s.lang||"Subtitle "+(i+1)}</button>)}</div>}</div>}<button onClick={toggleFullscreen}>{fullscreen?"⤢":"⛶"}</button>{isMedia&&<button className="downloadBtn" onClick={startDownload}>⇩</button>}{isHls&&<span className="downloadDisabled" title="HLS remux is not enabled yet">⇩</span>}</div></div>}
 {nextCountdown>0&&<div className="nextOverlay"><strong>Next episode in {nextCountdown}</strong><span>{nextTitle}</span><div><button onClick={goNext} disabled={nextLoading}>{nextLoading?"Loading…":"Play now"}</button><button onClick={()=>setNextCountdown(0)}>Cancel</button></div></div>}
 </div>{resume>0&&<p className="resumeNote">Resuming from {fmt(resume)}</p>}{downloadMessage&&<div className="playerNotice"><h2>Download unavailable</h2><p>{downloadMessage}</p></div>}{error&&<div className="playerNotice"><h2>Playback error</h2><p>{error}</p><code>{u}</code></div>}</main>
}
function safeFileName(x:string){return (x.replace(/[^a-z0-9._ -]/gi,"").trim()||"Drift").slice(0,80)}
function guessExt(u:string){const m=u.match(/\.(mp4|webm|ogg)(?:\?|$)/i);return m?"."+m[1].toLowerCase():".mp4"}
function fmt(n:number){if(!Number.isFinite(n)||n<0)return "0:00";const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=Math.floor(n%60);return h?(h+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")):(m+":"+String(s).padStart(2,"0"))}
export default function Watch(){return <Suspense fallback={<main className="watch">Loading…</main>}><P/></Suspense>}