"use client";
import {useEffect,useState} from "react";
type Addon={id:string;name:string;description?:string;logo?:string;url:string;resources?:unknown[];catalogs?:{id:string;type:string;name:string;extra?:unknown[]}[]};
type Meta={id:string;type:string;name:string;poster?:string;background?:string;description?:string;releaseInfo?:string;genres?:string[];videos?:{id:string;title:string;released?:string;thumbnail?:string}[]};
type Stream={name?:string;title?:string;url?:string;ytId?:string;infoHash?:string;behaviorHints?:Record<string,unknown>};
const KEY="drift-addons",LIB="drift-library";
export default function Home(){const [addons,setAddons]=useState<Addon[]>([]);const [url,setUrl]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [selected,setSelected]=useState<Meta|null>(null);const [selectedAddon,setSelectedAddon]=useState<Addon|null>(null);const [streams,setStreams]=useState<Stream[]>([]);const [query,setQuery]=useState("");
useEffect(()=>{try{setAddons(JSON.parse(localStorage.getItem(KEY)||"[]"))}catch{}},[]);
function save(a:Addon[]){setAddons(a);localStorage.setItem(KEY,JSON.stringify(a))}
async function install(){setError("");setLoading(true);try{const r=await fetch("/api/addon/manifest?url="+encodeURIComponent(url));const j=await r.json();if(!r.ok)throw Error(j.error||"Could not load addon");const a={...j,url};save([...addons.filter(x=>x.url!==url),a]);setUrl("")}catch(e){setError(e instanceof Error?e.message:"Failed")}finally{setLoading(false)}}
async function openMeta(a:Addon,m:Meta){setSelected(m);setSelectedAddon(a);setStreams([]);const r=await fetch("/api/addon/resource?addon="+encodeURIComponent(a.url)+"&resource=meta&type="+m.type+"&id="+encodeURIComponent(m.id));if(r.ok){const j=await r.json();setSelected(j.meta?.[0]||m)}const s=await fetch("/api/addon/resource?addon="+encodeURIComponent(a.url)+"&resource=stream&type="+m.type+"&id="+encodeURIComponent(m.id));if(s.ok){const j=await s.json();setStreams(j.streams||[])}}
function library(){if(!selected)return;const old=JSON.parse(localStorage.getItem(LIB)||"[]");if(!old.some((x:Meta)=>x.id===selected.id)){localStorage.setItem(LIB,JSON.stringify([...old,selected]))}}
return <main><header><a href="/" className="brand">DRIFT</a><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your addons..." /><a className="nav" href="/library">Library</a><a className="nav" href="/addons">Addons</a></header><section className="hero"><span className="eyebrow">YOUR CONTENT. YOUR ADDONS.</span><h1>One home for your media.</h1><p>Install compatible addons, browse catalogs and resolve streams in one clean interface.</p></section><section className="panel"><h2>Add an addon</h2><div className="install"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/manifest.json"/><button onClick={install} disabled={loading||!url}>{loading?"Adding…":"Add addon"}</button></div>{error&&<p className="error">{error}</p>}</section>{addons.map(a=><AddonSection key={a.url} addon={a} query={query} onOpen={openMeta}/>)}{addons.length===0&&<section className="empty"><h2>Nothing installed yet</h2><p>Add a compatible Stremio addon manifest above to populate Drift.</p></section>}{selected&&<div className="modal"><div className="modalCard"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="detail">{selected.poster&&<img src={selected.poster}/>}<div><span>{selected.type}</span><h2>{selected.name}</h2><p>{selected.description}</p><p>{selected.releaseInfo}</p><div className="actions"><button onClick={library}>＋ Library</button></div><div className="streams">{streams.map((s,i)=>s.url?<a key={i} href={"/watch?url="+encodeURIComponent(s.url)+"&title="+encodeURIComponent(selected.name)} className="stream">{s.name||s.title||"Play"} ▶</a>:<span key={i} className="stream">{s.name||s.title||"Unsupported stream transport"}</span>)}</div></div></div></div></div>}</main>}
function AddonSection({addon,query,onOpen}:{addon:Addon;query:string;onOpen:(a:Addon,m:Meta)=>void}){const [items,setItems]=useState<Meta[]>([]);useEffect(()=>{let dead=false;setItems([]);const load=async()=>{for(const c of addon.catalogs||[]){if(query&&!c.extra?.some((e:any)=>e?.name==="search"))continue;const extra=query?"&search="+encodeURIComponent(query):"";const r=await fetch("/api/addon/resource?addon="+encodeURIComponent(addon.url)+"&resource=catalog&type="+c.type+"&id="+encodeURIComponent(c.id)+extra);if(r.ok){const j=await r.json();if(!dead)setItems(x=>[...x,...(j.metas||[]).slice(0,20)])}}};load();return()=>{dead=true}},[addon.url,query]);if(!items.length)return null;return <section className="catalog"><div className="sectionHead"><h2>{addon.name}</h2><span>{items.length} items</span></div><div className="grid">{items.map((m,i)=><button className="card" key={m.id+"-"+i} onClick={()=>onOpen(addon,m)}>{m.poster?<img src={m.poster}/>:<div className="posterFallback">DRIFT</div>}<strong>{m.name}</strong><small>{m.releaseInfo||m.type}</small></button>)}</div></section>}
