"use client";
import {useEffect,useState} from "react";

type Extra={name:string;isRequired?:boolean;options?:string[]};
type A={id:string;name:string;description?:string;logo?:string;url:string;resources?:unknown[];catalogs?:{id:string;type:string;name:string;extra?:Extra[]}[];types?:string[];behaviorHints?:{configurable?:boolean};config?:unknown[]};
type S={name?:string;title?:string;url?:string;externalUrl?:string;infoHash?:string;behaviorHints?:Record<string,unknown>};

function norm(v:string){v=v.trim();return v.startsWith("stremio://")?"https://"+v.slice(10):v}
function playHref(s:S){const h:any=s.behaviorHints||{};const q=new URLSearchParams({url:s.url||"",title:s.title||s.name||"Stream",ph:btoa(JSON.stringify(h.proxyHeaders?.request||{}))});return "/watch?"+q.toString()}

export default function Addons(){
 const [a,setA]=useState<A[]>([]),[url,setUrl]=useState(""),[loading,setLoading]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[id,setId]=useState(""),[type,setType]=useState<"movie"|"series">("movie"),[streams,setStreams]=useState<S[]>([]),[testing,setTesting]=useState(false);
 useEffect(()=>{try{setA(JSON.parse(localStorage.getItem("drift-addons")||"[]"))}catch{}},[]);
 function save(x:A[]){setA(x);localStorage.setItem("drift-addons",JSON.stringify(x))}
 async function install(){setMsg("");setErr("");setLoading(true);try{const u=norm(url);const r=await fetch("/api/addon/manifest?url="+encodeURIComponent(u));const j=await r.json();if(!r.ok)throw Error(j.error||"Could not load addon");if(!j.id||!j.name)throw Error("Invalid addon manifest.");save([...a.filter(x=>x.url!==u),{...j,url:u}]);setUrl("");setMsg("Installed “"+j.name+"”.")}catch(e){setErr(e instanceof Error?e.message:"Failed to install addon")}finally{setLoading(false)}}
 async function resolve(){if(!id.trim()){setErr("Enter a movie/series ID, for example tt0133093.");return}setErr("");setMsg("");setTesting(true);setStreams([]);const providers=a.filter(x=>Array.isArray(x.resources)&&x.resources.some((r:any)=>r==="stream"||r?.name==="stream"));if(!providers.length){setErr("Install a stream-capable addon first.");setTesting(false);return}try{const rs=await Promise.all(providers.map(async x=>{try{const r=await fetch("/api/addon/resource?addon="+encodeURIComponent(x.url)+"&resource=stream&type="+type+"&id="+encodeURIComponent(id.trim()));if(!r.ok)return[];const j=await r.json();return(j.streams||[]).map((s:S)=>({...s,__addon:x.name}))}catch{return[]}}));const all=rs.flat();setStreams(all);setMsg(all.length?"Found "+all.length+" stream(s).":"No streams were returned for that ID.")}finally{setTesting(false)}}
 function rm(u:string){const n=a.filter(x=>x.url!==u);save(n)}
 return <main><header><a className="brand" href="/">DRIFT</a><a className="nav" href="/library">Library</a></header>
 <section className="hero compactHero"><span className="eyebrow">ADDON MANAGER</span><h1>Bring your sources.</h1><p>Install compatible Stremio addons. Drift keeps them local and uses them to build your catalogs and playback options.</p></section>
 <section className="panel"><h2>Add an addon</h2><div className="install"><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==="Enter"&&install()} placeholder="https://example.com/manifest.json or stremio://..."/><button onClick={install} disabled={loading||!url}>{loading?"Adding…":"Add addon"}</button></div>{err&&<p className="error">{err}</p>}{msg&&<p className="success">{msg}</p>}</section>
 <details className="panel advancedPanel"><summary>Advanced · Stream Resolver</summary><div className="advancedBody"><h2>Stream Resolver</h2><p>Test installed stream-capable addons directly with a title ID.</p><div className="install"><select value={type} onChange={e=>setType(e.target.value as "movie"|"series")}><option value="movie">Movie</option><option value="series">Series</option></select><input value={id} onChange={e=>setId(e.target.value)} onKeyDown={e=>e.key==="Enter"&&resolve()} placeholder="IMDb ID, e.g. tt0133093"/><button onClick={resolve} disabled={testing}>{testing?"Resolving…":"Resolve streams"}</button></div>{streams.length>0&&<div className="streams">{streams.map((s,i)=>s.url?<a className="stream" key={i} href={playHref(s)}>{s.name||s.title||"Play"} ▶</a>:s.externalUrl?<a className="stream" key={i} href={s.externalUrl} target="_blank" rel="noreferrer">{s.name||s.title||"Open external"} ↗</a>:<span className="stream" key={i}>{s.name||s.title||s.infoHash||"Unsupported stream"}</span>)}</div>}</div></details>
 <section className="installedSection"><div className="sectionHead"><h2>Installed addons</h2><span>{a.length}</span></div><div className="addonList">{a.map(x=><article className="addon" key={x.url}>{x.logo&&<img src={x.logo}/>}<div><h2>{x.name}</h2><p>{x.description}</p><small>{(x.types||[]).join(", ")||"unknown"} · {(x.resources||[]).map((r:any)=>typeof r==="string"?r:r?.name).filter(Boolean).join(", ")||"no resources"}</small><small>{x.url}</small></div><button onClick={()=>rm(x.url)}>Remove</button></article>)}</div>{!a.length&&<section className="empty"><h2>No addons installed</h2></section>}</section>
 </main>
}